### ISSUE TITLE
woocommerce purchase data.

### ISSUE THREAD

**Issue by adahox** [dontbetriangle/Woocommerce-Mautic-Plugin#1]
there's some way to send purchase data to mautic? somethink like  price and category product?

**Comment by SinAndTonic** [comment]
Not at the moment im afraid. There is no way to currently do this with Mautic. They would need to implement a field in each contact which allowed purchase data to be pushed onto an array or the likes. 

Might be possible to do this with the api by retrieving data, adding the new data then sending back, but to be honest you would not be able to do anything useful with it in Mautic at this stage anyway.
